locale = "tr"
label = "Türkçe"
weight = 2
title = "Lore Playing"

[params]
  displayName = "Türkçe"
  isoCode = "tr"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/lp-logo.png"
  description = "Lore Playing Logo"
